vim.tbl_extend("error", lvim.plugins, require("user.plugins.ansible").plugins)
vim.tbl_extend("error", lvim.plugins, require("user.plugins.coding").plugins)
vim.tbl_extend("error", lvim.plugins, require("user.plugins.editor").plugins)
vim.tbl_extend("error", lvim.plugins, require("user.plugins.extras").plugins)
vim.tbl_extend("error", lvim.plugins, require("user.plugins.go").plugins)
vim.tbl_extend("error", lvim.plugins, require("user.plugins.python").plugins)
vim.tbl_extend("error", lvim.plugins, require("user.plugins.ui").plugins)
