---
project_name: dotfiles
before:
  hooks:
    - go mod download
release:
  prerelease: false
builds:
  - id: dotfiles 
    main: ./pkg/cmd/dotfiles-cli 
    env:
      - CGO_ENABLED=0
      - CGO_CPPFLAGS="-I/usr/include"
      - CGO_LDFLAGS="-L/usr/lib -lpthread -lrt -lstdc++ -lm -lc -lgcc"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
