---
- name: Dotfiles setup
  hosts: local

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    dotfiles_dir: "{{ playbook_dir }}"
    dotfiles_dir_files: "{{ dotfiles_dir }}/files"

  pre_tasks:
    - name: Include OS specific vars
      ansible.builtin.include_vars: "vars/{{ ansible_os_family | lower }}.yaml"
      tags: always

    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"
      tags: always

  roles:
    #
    # Packages
    #
    - role: packages
      tags: packages
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished packages role"
      tags: packages
    #
    # System
    #
    - role: system
      tags: system
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished system role"
      tags: system
    #
    # Git
    #
    - role: git
      tags: git
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished git role"
      tags: git
    #
    # Terminal
    #
    - role: terminal/zsh
      tags:
        - zsh
        - terminal
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished terminal/zsh role"
      tags:
        - zsh
        - terminal
    - role: terminal/tmux
      tags:
        - tmux
        - terminal
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished terminal/tmux role"
      tags:
        - tmux
        - terminal
    - role: terminal/ranger
      tags:
        - ranger
        - terminal
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished terminal/ranger role"
      tags:
        - ranger
        - terminal
    #
    # Editors
    #
    - role: editors/vim
      tags:
        - vim
        - editors
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/vim role"
      tags:
        - vim
        - editors
    - role: editors/emacs
      when: emacs_editor_enabled | default(false) | bool
      tags:
        - emacs
        - editors
    - role: notifications/telegram
      when:
        - telegram_notifications_enabled | default(false) | bool
        - emacs_editor_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/emacs role"
      tags:
        - vim
        - editors
    - role: editors/vscode
      tags:
        - vscode
        - editors
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/vscode role"
      tags:
        - vscode
        - editors
    - role: editors/lunarvim
      tags:
        - lunarvim
        - editors
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/lunarvim role"
      tags:
        - lunarvim
        - editors
    #
    # Filesystem
    #
    - role: filesystem/symlink
      tags:
        - symlink
        - filesystem
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished filesystem/symlink role"
      tags:
        - symlink
        - filesystem
    - role: filesystem/install
      when: filesystem_install_enabled | default(false) | bool
      tags:
        - install
        - filesystem
    - role: notifications/telegram
      when:
        - telegram_notifications_enabled | default(false) | bool
        - filesystem_install_enabled | default(false) | bool
      telegram_message: "dotfiles: finished filesystem/install role"
      tags:
        - install
        - filesystem
    #
    # Misc
    #
    - role: misc
      tags: misc
    - role: notifications/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished misc role"
      tags: misc
