---
- name: Dotfiles setup
  hosts: local

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    dotfiles_dir: "{{ playbook_dir }}"
    dotfiles_dir_files: "{{ dotfiles_dir }}/files"

  pre_tasks:
    - name: Include OS specific vars
      ansible.builtin.include_vars: "vars/{{ ansible_os_family | lower }}.yml"
      tags: always

    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: always

  roles:
    - role: packages
      tags: packages
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished packages role"
      tags: packages
    - role: git
      tags: git
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished git role"
      tags: git
    - role: terminal/zsh
      tags:
        - zsh
        - terminal
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished terminal/zsh role"
      tags:
        - zsh
        - terminal
    - role: terminal/tmux
      tags:
        - tmux
        - terminal
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished terminal/tmux role"
      tags:
        - tmux
        - terminal
    - role: editors/vim
      tags:
        - vim
        - editors
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/vim role"
      tags:
        - vim
        - editors
    - role: editors/emacs
      tags:
        - vim
        - editors
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/emacs role"
      tags:
        - vim
        - editors
    - role: editors/vscode
      tags:
        - vscode
        - editors
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished editors/vscode role"
      tags:
        - vscode
        - editors
    - role: filesystem/symlink
      tags:
        - symlink
        - filesystem
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished filesystem/symlink role"
      tags:
        - symlink
        - filesystem
    - role: filesystem/install
      tags:
        - install
        - filesystem
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished filesystem/install role"
      tags:
        - install
        - filesystem
    - role: system
      tags: system
    - role: utils/telegram
      when: telegram_notifications_enabled | default(false) | bool
      telegram_message: "dotfiles: finished filesystem/system role"
      tags: system
