---
- name: Ensure apt cache is updated
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true

- name: Ensure snap is present
  become: true
  ansible.builtin.apt: name=snapd state=present

- name: Ensure apt repositories are present
  become: true
  ansible.builtin.apt_repository:
    name: "{{ item.name | default(item )}}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ packages_apt_repos }}"

- name: Ensure apt packages are present
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.staet | default('present') }}"
  loop: "{{ packages_apt_packages }}"

- name: Ensure snap is present
  become: true
  ansible.builtin.apt:
    name: snapd
    state: present

- name: Ensure snap apps are present
  become: true
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    classic: "{{ item.classic | default(true) | bool }}"
  loop: "{{ packages_snap_apps }}"
