---
- name: Include debian specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Ensure GOPATH exists
  ansible.builtin.file:
    path: "{{ home_dir }}/go"
    state: directory
    mode: 0751

- name: Install go apps
  ansible.builtin.command:
    cmd: "go install {{ item.package }}"
    creates: "{{ item.creates }}"
  environment:
    GOPATH: "{{ home_dir }}/go"
    GOROOT: "{{ packages_go_root }}"
    PATH: "{{ lookup('env', 'PATH') }}:{{ homebrew_bin_path }}"
  loop: "{{ packages_go_packages }}"
