---
- name: Include darwin specific tasks
  ansible.builtin.include_tasks: darwin.yaml
  when: ansible_os_family == "Darwin"
- name: Include debian specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Download oh-my-zsh install script
  ansible.builtin.get_url:
    url: "{{ zsh_oh_my_zsh_install_script_url }}"
    dest: /tmp/oh-my-zsh-install.sh
    mode: 0751

- name: Ensure oh-my-zsh is installed
  ansible.builtin.command:
    cmd: /tmp/oh-my-zsh-install.sh
    creates: "{{ zsh_oh_my_zsh_install_path }}"

- name: Ensure oh-my-zsh plugins are present
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
    update: false
    depth: 1
  loop: "{{ zsh_oh_my_zsh_plugins }}"

- name: Set user shell to zsh.
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
