---
- name: Ensure Emacs-Mac tap is present
  homebrew_tap: name=railwaycat/emacsmacport state=present

- name: Ensure Emacs-Mac is installed
  homebrew:
    name: emacs-mac
    state: present
    install_options: with-modules

- name: Ensure Doom Emacs is installed
  git:
    repo: "{{ doom_emacs_repo }}"
    version: develop
    dest: "{{ doom_emacs_install_path }}"
    update: false
    depth: 1

- name: Ensure Doom Emacs directory is in place.
  stat: "path={{ doom_emacs_config_dir }}"
  register: doom_emacs_dir
  check_mode: false

- name: Install Doom Emacs
  expect:
    command: doom install
    responses:
      (.*)envar(.*): "y"
      (.*)fonts(.*): "y"
  when: not doom_emacs_dir.stat.exists
