---
- name: Ensure Emacs-Mac tap is present.
  homebrew_tap: name=railwaycat/emacsmacport state=present

- name: Ensure Emacs-Mac is installed.
  homebrew:
    name: emacs-mac
    state: present
    install_options: with-modules

- name: Ensure Doom Emacs directories are in place.
  ansible.builtin.stat: "path={{ item }}"
  register: doom_emacs_dirs
  check_mode: false
  loop:
    - "{{ doom_emacs_config_dir }}"
    - "{{ doom_emacs_binary }}"

# Run the block if any of the directories above is absent.
- block:
  - name: Ensure doom_emacs_install_path is empty.
    ansible.builtin.file:
      path: "{{ doom_emacs_install_path }}"
      state: absent

  - name: Ensure Doom Emacs is installed.
    ansible.builtin.git:
      repo: "{{ doom_emacs_repo }}"
      version: master
      dest: "{{ doom_emacs_install_path }}"
      update: false
      depth: 1

  - name: Ensure proper permissions on doom_emacs_binary.
    ansible.builtin.file:
      path: "{{ doom_emacs_binary }}/doom"
      state: file
      mode: 0775

  - name: Install Doom Emacs.
    ansible.builtin.command: "{{ doom_emacs_binary }}/doom --yes install"
    changed_when: true
  when: "not (doom_emacs_dirs.results | map(attribute='stat') | map(attribute='exists') | min)"
