---
- name: Ensure Emacs-Mac tap is present.
  homebrew_tap: name=railwaycat/emacsmacport state=present

- name: Ensure Emacs-Mac is installed.
  homebrew:
    name: emacs-mac
    state: present
    install_options: with-modules

- name: Ensure Doom Emacs directory is in place.
  stat: "path={{ doom_emacs_config_dir }}"
  register: doom_emacs_dir
  check_mode: false

- block:
  - name: Ensure doom_emacs_install_path is empty.
    file:
      path: "{{ doom_emacs_install_path }}"
      state: absent

  - name: Ensure Doom Emacs is installed.
    git:
      repo: "{{ doom_emacs_repo }}"
      version: develop
      dest: "{{ doom_emacs_install_path }}"
      update: false
      depth: 1

  - name: Ensure proper permissions on doom_emacs_binary.
    file:
      path: "{{ doom_emacs_binary }}/doom"
      state: file
      mode: 0775

  - name: Install Doom Emacs.
    expect:
      command: "{{ doom_emacs_binary }}/doom install"
      timeout: 210
      responses:
        (.*)envvar(.*): "y"
        (.*)fonts(.*): "y"
  when: not doom_emacs_dir.stat.exists
