---
- name: Collect install files.
  ansible.builtin.command: "find -H {{ dotfiles_files }} -name 'install.sh'"
  register: install_files
  failed_when: false
  check_mode: false
  changed_when: false

# Use shell because envs are required to run an install.sh script.
- name: Run install files. # noqa 305
  ansible.builtin.shell: "{{ item }}"
  register: install_result
  changed_when: false
  when: '"item" not in blacklisted_install_files'
  loop: "{{ install_files.stdout | split('\n') | flatten(1) }}"
