---
- name: Collect install files.
  command: "find -H {{ dotfiles_files }} -name 'install.sh'"
  register: install_files
  failed_when: false
  check_mode: false
  changed_when: false

# In each install.sh script we check for the existence of a module.
# So it is okay if we do not install anything.
- name: Run install files.
  command: "{{ item }}"
  with_items: "{{ install_files.stdout | split('\n') }}"
  changed_when: false
  when: '"item" not in blacklisted_install_files'
