---
- name: Configure MacOS defaults.
  ansible.builtin.command: "{{ macos_files }}/set-defaults.sh"
  changed_when: false

- name: Add fonts.
  ansible.builtin.copy:
    src: "{{ macos_files }}/fonts/"
    dest: "/Library/Fonts"
    mode: 0775
  become: yes

- name: Add keyboard layouts.
  ansible.builtin.copy:
    src: "{{ macos_files }}/keyboard-layouts/"
    dest: '/Library/Keyboard\ Layouts'
    mode: 0775
  become: yes

- name: Get current iTerm profile.
  ansible.builtin.command: defaults read com.googlecode.iterm2
  register: terminal_config
  changed_when: false
  check_mode: false
  failed_when: false

- name: Configure iTerm.
  ansible.builtin.shell: >
    defaults write com.googlecode.iterm2 PrefsCustomFolder
    -string "{{ home_prefix }}/.itermcfg/"
    &&
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder
    -bool true
  changed_when: false
  when: >
    'PrefsCustomFolder' not in terminal_config.stdout
    or 'does not exist' in terminal_config.stdout
