---
- name: Update dotfiles CLI
  hosts: local

  vars:
    dotfiles_dir: "{{ lookup('env', 'DOTFILES') }}"

  tasks:
    - name: Install dotfiles-cli
      community.general.make:
        chdir: "{{ dotfiles_dir }}"
        target: cli
