# utf8 is on
setw -q -g utf8 on
set -q -g status-utf8 on

# Terminal
set -ag terminal-overrides ",xterm-256color:RGB"

# Rename window to reflect current program
setw -g automatic-rename off

# Renumber windows when a window is closed
set -g renumber-windows on

# Redraw status line every 10 seconds
set -g status-interval 10

# Activity
set -g bell-action none
set -g visual-bell off
set -g monitor-activity off
set -g visual-activity off

# Title
set -g set-titles on
set -g set-titles-string 'tmux | #S | #W'

setw -g xterm-keys on

# Don't wrap searches; it's super confusing given tmux's reverse-ordering of position info in copy mode.
set -w -g wrap-search off

# Switch to last active session if destroyed
set -g detach-on-destroy off
