---
#
# Misc
#
booleans_map:
  "Y": true
  "y": true
  "YES": true
  "yes": true
  "n": false
  "N": false
  "NO": false
  "no": false
go_arch_map:
  i386: "386"
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "armv7"
  armv6l: "armv6"
go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
#
# Zsh
#
zsh_oh_my_zsh_plugins:
  - repo: "https://github.com/agkozak/zsh-z.git"
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-z"
  - repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-completions"
    version: "0.35.0"
  - repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-autosuggestions"
  - repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-syntax-highlighting"
  - repo: https://github.com/marlonrichert/zsh-autocomplete.git
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-autocomplete"
    version: "23.07.13"
  - repo: https://github.com/joshskidmore/zsh-fzf-history-search
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-fzf-history-search"
    version: master
  - repo: https://github.com/jeffreytse/zsh-vi-mode
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-vi-mode"
    version: "v0.11.0"
  - repo: https://github.com/softmoth/zsh-vim-mode.git
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/zsh-vim-mode"
    version: main
  - repo: https://github.com/mroth/evalcache.git
    dest: "{{ zsh_oh_my_zsh_plugins_path }}/evalcache"
    version: master
#
# Ranger
#
ranger_plugins:
  - repo: "https://github.com/jchook/ranger-zoxide.git"
    dest: "{{ ranger_plugins_path }}/zoxide"
  - repo: "https://github.com/cdump/ranger-devicons2"
    dest: "{{ ranger_plugins_path }}/devicons2"
  - repo: "https://github.com/MuXiu1997/ranger-fzf-filter.git"
    dest: "{{ ranger_plugins_path }}/fzf-filter"
    version: main
#
# Go
#
packages_go_packages:
  - name: gofumpt
    package: "mvdan.cc/gofumpt@latest"
  - name: cobra-cli
    package: "github.com/spf13/cobra-cli@latest"
  - name: goimports
    package: "golang.org/x/tools/cmd/goimports@latest"
  - name: godoc
    package: "golang.org/x/tools/cmd/godoc@latest"
  - name: gopls
    package: "golang.org/x/tools/gopls@latest"
  - name: protoc-gen-go
    package: "google.golang.org/protobuf/cmd/protoc-gen-go@latest"
  - name: protoc-gen-go-grpc
    package: "google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"
  - name: swag
    package: "github.com/swaggo/swag/cmd/swag@latest"
  - name: nilaway
    package: "go.uber.org/nilaway/cmd/nilaway@latest"
#
# VSCode
#
vscode_extensions:
  # Themes
  - dracula-theme.theme-dracula
  - Equinusocio.vsc-material-theme
  - PKief.material-icon-theme
  - johnpapa.vscode-peacock
  # Code
  - formulahendry.code-runner
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-russian
  - austin.code-gnu-global
  - aaron-bond.better-comments
  - esbenp.prettier-vscode
  - Gruntfuggly.todo-tree
  - mattn.Lisp
  # Remote
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-containers
  # Python
  - ms-python.python
  - KevinRose.vsc-python-indent
  - ms-python.vscode-pylance
  - njpwerner.autodocstring
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-slideshow
  # Golang
  - golang.go
  - premparihar.gotestexplorer
  # C++
  - danielpinto8zz6.c-cpp-compile-run
  - ms-vscode.cpptools
  - ms-vscode.makefile-tools
  # Latex
  - James-Yu.latex-workshop
  - nickfode.latex-formatter
  - tecosaur.latex-utilities
  - torn4dom4n.latex-support
  - twday.bibmanager
  # Json
  - heptio.jsonnet
  - xrc-inc.jsonnet-formatter
  - ZainChen.json
  - randrade23.beautify-json
  # Ansible
  - redhat.ansible
  - redhat.vscode-yaml
  - wholroyd.jinja
  # SQL
  - mtxr.sqltools
  - mtxr.sqltools-driver-mysql
  - mtxr.sqltools-driver-pg
  - ultram4rine.sqltools-clickhouse-driver
  # For VSCode
  - vscodevim.vim
  - DavidAnson.vscode-markdownlint
  - sensourceinc.vscode-sql-beautify
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - redhat.vscode-yaml
  - zxh404.vscode-proto3
  - ionutvmi.path-autocomplete
  - VisualStudioExptTeam.intellicode-api-usage-examples
  - VisualStudioExptTeam.vscodeintellicode
  - alefragnani.project-manager
  # Git
  - eamodio.gitlens
  - felipecaputo.git-project-manager
  - GitHub.vscode-pull-request-github
  - GitLab.gitlab-workflow
  - kahole.magit
  # Other
  - tomoki1207.pdf
  - EditorConfig.EditorConfig
  - ericadamski.carbon-now-sh
  - GrapeCity.gc-excelviewer
  - shd101wyy.markdown-preview-enhanced
  - 42Crunch.vscode-openapi
