---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path | default(item) }}"
    mode: "{{ item.mode | default('751') }}"
    state: directory
  loop:
    - "{{ home_dir }}/Desktop/Screenshots"

- name: Copy MacOS files
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('755') }}"
  loop:
    - src: "{{ system_macos_files }}/fonts/"
      dest: "/Library/Fonts"
    - src: "{{ system_macos_files }}/keyboard-layouts/"
      dest: '/Library/Keyboard Layouts'

- name: Configure MacOS defaults
  become: "{{ item.become | default(false) | bool }}"
  community.general.osx_defaults:
    domain: "{{ item.domain | default('NSGlobalDomain')}}"
    key: "{{ item.key }}"
    type: "{{ item.type | default('string') }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_macos_defaults }}"

- name: Make folders visible
  become: true
  ansible.builtin.command: "chflags nohidden {{ item }}"
  changed_when: false
  loop:
    - ~/Library
    - /Volumes
