alias d='docker $*'
alias d-c='docker-compose $*'
alias ddelcnts='docker rm $(docker ps -a -q -f status=exited)'
alias dclean='docker system prune -a'
alias dhardclean='docker volume ls -qf dangling=true | xargs docker volume rm'
alias dcleandangling='docker rmi -f $(docker images -f "dangling=true" -q)'
