---
# All
packages_go_packages: []
# Darwin
homebrew_use_brewfile: false
homebrew_cask_appdir: /Applications
# Debian
packages_apt_repos: []
packages_apt_packages: []
packages_snap_apps: []
packages_homebrew_packages: []
