alias d='docker $*'
alias dcompose='docker-compose $*'
alias ddelstopped='docker rm $(docker ps -a -q)'
alias dclean='docker system prune -a'
alias dhardclean='docker volume ls -qf dangling=true | xargs docker volume rm'
alias dcleandangling='docker rmi -f $(docker images -f "dangling=true" -q)'
