#!/usr/bin/env bash
#
# bootstrap installs things.
source ./script/prompt

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ""

setupGitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info "setup gitconfig"

    git_credential="cache"
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential="osxkeychain"
    fi

    user " - What is your github author name?"
    read -e git_authorname
    user " - What is your github author email?"
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success "gitconfig"
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

installDotfiles () {
  info "installing dotfiles"

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setupGitconfig
installDotfiles

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source $HOME/.dotfiles/bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

setupSymlinks () {
  # symlink .dotfiles tmux to ~
  rm -rf $HOME/.tmux
  mkdir $HOME/.tmux
  ln -s $HOME/.dotfiles/tmux/responsive $HOME/.tmux/responsive && success "symlink for $HOME/.tmux/responsive created"
  # nvim symlink
  rm -rf $HOME/.config/nvim/init.vim
  ln -s $HOME/.dotfiles/vim/vimrc.symlink $HOME/.config/nvim/init.vim && success "symlink for nvim config created"
  # Karabiner symlink
  rm -rf $HOME/.config/karabiner
  ln -s $HOME/.dotfiles/karabiner $HOME/.config/karabiner && success "symlink for karabiner config created"
  # symlink for Emacs App
  rm -rf /Applications/Emacs.app
  ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app && success "symlink for better GNU Emacs created"
  # symlink for Doom-Emacs config
  rm -rf $HOME/.doom.d
  ln -s $HOME/emacs $HOME/.doom.d && success "symlink for Doom-Emacs created"
  # symlink VSCode User Settings
  if [ -d $HOME/Library/Application\ Support/Code/User ] ; then
    echo "Creating symlinks for VSCode..."
    echo ""
    rm -rf $HOME/Library/Application\ Support/Code/User/settings.json
    rm -rf $HOME/Library/Application\ Support/Code/User/keybindings.json
    ln -s $HOME/.dotfiles/vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json && success "settings.json for vs code symlink created"
    ln -s $HOME/.dotfiles/vscode/keybindings.json $HOME/Library/Application\ Support/Code/User/keybindings.json && success "keybindings.json for vs code symlink created"
  else
    info "symlink for vs code settings not created"
    echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
  fi
}

colors () {
  # colorls setup
  sudo gem install colorls -n /usr/local/bin && success "ls colors have been configured"
}

configureDoomEmacs() {
  $HOME/.emacs.d/bin/doom install
}

configureVim() {
  nvim +PluginInstall +qa
  cd $HOME/.vim/bundle/YouCompleteMe && python3 install.py --all && ./install.py
}

itermConfig () {
  # iterm2 config
  read -p "Do you currently use iTerm2 and would you like to set custom colors? y/n " -n 1 -r
  echo ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    # Specify the preferences directory
    defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
      if [[ $? -eq 0 ]]
      then
          success "successfully configured iTerm2 to use custom colors..."
      else
          fail "failed to apply custom colors..." >&2
  fi
  else 
      info "You chose not to use iTerm2 or custom colors."
  fi
}

fontSetup () {
  # install Source Code Pro nerd font
  for font in $HOME/.dotfiles/fonts/*; do
    sudo cp $font /Library/Fonts
  done
  success "Source Code Pro font copied successfully!"
}

configFix () {
  # .config permissions fix
  if [ ! -d "$HOME/.config" ]; then
    info "$HOME/.config doesn't exist, nothing to fix"
  else
    sudo chown $(whoami) $HOME/.config 
    success ".config permissions fixed"
  fi
}

configureVim
configureDoomEmacs
setupSymlinks
colors
itermConfig
fontSetup
configFix

success "macOS terminal installed!"
