alias clr='clear'
alias reload='omz reload'

alias c='z'
alias cz='zi'
alias cs='cd_with_fzf'
alias cd='z'
alias cdi='zi'
alias g='rg'
alias f='fd'
alias cat='bat'
alias df='duf'
alias du='ncdu'
alias vim='nvim'
alias rm='trash'
alias lgit='lazygit'
alias ls='exa --icons --color=always'
alias ll='exa --icons --color=always -l'
alias la='exa --icons --color=always -la'
alias lt='exa --icons --color=always -T'
alias pass='gopass'
alias pinentry='pinentry-mac'
alias tnotif='terminal-notifier'

alias zshconfig='nvim ~/.zshrc'
alias ohmyzsh='nvim ~/.oh-my-zsh'
alias config='/usr/bin/git --git-dir=/Users/$(whoami)/.cfg/ --work-tree=/Users/$(whoami)'
alias cur_dir='echo ${PWD##*/}'
alias chsize='ls -lh'
alias chdirsize='du -hs'
alias topndir='du -sxh ./* | sort -rh'
alias isscreen='echo $STY'
alias chnumber='ls -1 | wc -l'
