alias clr='clear'
alias reload='omz reload'

alias c='z'
alias cz='zi'
alias cs='cd_with_fzf'
alias cd='z'
alias cdi='zi'
alias cat='bat'
alias df='duf'
alias du='ncdu'
alias vim='lvim'
alias rm='trash'
alias ls='exa --icons --color=always'
alias ll='exa --icons --color=always -l'
alias la='exa --icons --color=always -la'

alias zshconfig='lvim ~/.zshrc'
alias ohmyzsh='lvim ~/.oh-my-zsh'
alias config='/usr/bin/git --git-dir=/Users/$(whoami)/.cfg/ --work-tree=/Users/$(whoami)'
alias cur_dir='echo ${PWD##*/}'
alias chsize='ls -lh'
alias chdirsize='du -hs'
alias topndir='du -sxh ./* | sort -rh'
alias isscreen='echo $STY'
alias chnumber='ls -1 | wc -l'
