---
lunarvim_version: release-1.3/neovim-0.9
lunarvim_install_path: "{{ home_dir }}/.local"
lunarvim_install_script_url: "https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh"
