---
lunarvim_install_script_url: "https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh"
lunarvim_version: release-1.2/neovim-0.8
lunarvim_install_path: "{{ home_dir }}/.local"
