---
zsh_oh_my_zsh_repo: "https://github.com/robbyrussell/oh-my-zsh.git"
zsh_oh_my_zsh_install_script_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
zsh_oh_my_zsh_install_path: "{{ home_dir }}/.oh-my-zsh"
zsh_oh_my_zsh_plugins_path: "{{ home_dir }}/custom/plugins"
zsh_oh_my_zsh_plugins: []
