---
- name: Check doom emacs directories
  when: emacs_editor_enabled | default(false) | bool
  ansible.builtin.stat: "path={{ item }}"
  loop:
    - "{{ home_dir }}/.doom.d"
    - "{{ home_dir }}/.emacs.d/bin"
  register: _install_doom_emacs_dirs

- name: Update doom emacs configuration
  when:
    - emacs_editor_enabled | default(false) | bool
    - not (_install_doom_emacs_dirs.results | map(attribute='stat') | map(attribute='exists') | min)
  block:
    - name: Run doom emacs sync
      ansible.builtin.command: "{{ home_dir }}/.emacs.d/bin/doom sync -up"

    - name: Run doom emacs clean
      ansible.builtin.command: "{{ home_dir }}/.emacs.d/bin/doom clean"

    - name: Run doom emacs env
      ansible.builtin.command: "{{ home_dir }}/.emacs.d/bin/doom env"

    - name: Run doom emacs doctor
      ansible.builtin.command: "{{ home_dir }}/.emacs.d/bin/doom doctor"
      ignore_errors: true
