---
- name: Ensure cheat.sh install directory exists
  ansible.builtin.file:
    path: "{{ misc_cheat_sh_install_dir }}"
    state: directory
    mode: 0775

- name: Download cheat.sh script
  ansible.builtin.get_url:
    url: "{{ misc_cheat_sh_script_url }}"
    dest: "{{ misc_cheat_sh_install_path }}"
    mode: 0751
