---
- name: "Darwin: Ensure go is present"
  when: ansible_os_family == "Darwin"
  community.general.homebrew:
    name: go
    state: present

- name: "Fedora: Ensure go is present"
  when: ansible_os_family == "RedHat"
  become: true
  ansible.builtin.dnf:
    name: golang
    state: present
    update_cache: true

- name: Ensure go packages installed
  ansible.builtin.command:
    cmd: "go install {{ item.package }}"
    creates: "{{ lookup('env', 'GOPATH', default=home_dir + '/.go') }}/bin/{{ item.name }}"
  loop: "{{ misc_go_packages }}"
