---
- name: Include ani-cli tasks
  ansible.builtin.include_tasks: ani-cli.yaml
- name: Include cheat.sh tasks
  ansible.builtin.include_tasks: cheat.sh.yaml
- name: Include krew tasks
  ansible.builtin.include_tasks: krew.yaml
