---
- name: Include darwin specific tasks
  ansible.builtin.include_tasks: darwin.yaml
  when: ansible_os_family == "Darwin"
- name: Include debian specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Install vscode extensions
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code-extensions
    apply:
      become: true
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions: "{{ vscode_extensions }}"
